config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root :to => "home#index"
  get 'admins/index'

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :posts
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :category
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
	before_action :authenticate_user!
	def index
		
		
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    admins_index_path
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  	if params[:name]
  		a = Category.where(name: params[:name]).first
  		@posts = Post.where(category_id: a).order(id: :desc) if a && a.posts.count > 0
  	else
  		@posts = Post.all.order(id: :desc)
  	end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @categories = Category.all
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
    @categories = Category.all
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body, :image_url, :video_url, :category_id, :likes)
    end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/index.html.erb
<div id="page-transitions">
    
<div class="page-preloader page-preloader-dark">
    <img class="page-preload" src="/assets/preload.gif">
</div>
   
<div class="header header-dark">
    <a href="#" class="header-icon-1 show-left-sidebar"><i class="fa fa-navicon"></i></a>
    <a href="#" class="header-logo"></a>
    <a href="#" class="header-icon-4 show-right-sidebar"><i class="fa fa-envelope-o"></i></a>
</div>

<div id="page-content" class="page-content">
    <div id="page-content-scroll">
        <div class="content">    
            <div class="decoration"></div>
               <%= link_to "Sign out", destroy_user_session_path, method: 'delete', class: "login-button button button-small button-green button-fullscreen full-bottom" %>
               <%= link_to "Posts", posts_path, class: "login-button button button-small bg-blue-dark button-fullscreen full-bottom" %>
        </div>
    </div>
</div>

app/views/application/_sidebar_left.html.erb
<div class="sidebar-left">
    <div class="sidebar-scroll-left sidebar-dark-clean">         
        <div class="sidebar-image">
            <h3>Welcome to College Buzz</h3>
            <em>Once place for all news</em>
            <div class="sidebar-overlay"></div>
            <img src="assets/pictures/3.jpg" alt="img" class="responsive-image">
        </div>       
        <div class="sidebar-divider no-bottom no-top"></div>
        <p class="sidebar-divider">Navigation</p>
                         

        <div class="sidebar-menu">
            <a class="menu-item show-submenu" href="#">
                <i class="fa fa-home bg-red-dark"></i>
                <em>Home</em>
            </a> 
            <%= link_to root_path(name: "Educational"), {class: "default-link menu-item"}  do %>
                <i class="fa fa-graduation-cap bg-green-dark"></i>
                <em>Educational</em> 
            <% end %>
            <%= link_to root_path(name: "Sports"), {class: "default-link menu-item"}  do %>
                <i class="fa fa-street-view bg-orange-dark"></i>
                <em>Sports</em> 
            <% end %>
            <%= link_to root_path(name: "Politics"), {class: "default-link menu-item"}  do %>
                <i class="fa fa-flag bg-teal-dark"></i>
                <em>Politics</em> 
            <% end %>
            <%= link_to root_path(name: "Events"), {class: "default-link menu-item"}  do %>
                <i class="fa fa-users bg-green-dark"></i>
                <em>Events</em> 
            <% end %>
            <%= link_to root_path(name: "Entertainment"), {class: "default-link menu-item"}  do %>
                <i class="fa fa-film bg-gray-dark"></i>
                <em>Entertainment</em> 
            <% end %>
            <%= link_to root_path(name: "Announcements"), {class: "default-link menu-item"}  do %>
                <i class="fa fa-bullhorn bg-magenta-dark"></i>
                <em>Announcements</em> 
            <% end %>    
            <a class="menu-item close-sidebar" href="#">
                <i class="fa fa-times bg-red-dark"></i>
                <em>Close</em>
            </a>
        </div>
        <p class="sidebar-footer">Copyright 2015. All rights reserved</p>
    </div>
</div>

app/views/application/_sidebar_right.html.erb
<div class="sidebar-right">
    <div class="sidebar-scroll-right sidebar-dark-clean">     
        <div class="sidebar-image">
            <h3>Let's get in touch!</h3>
            <em>Send a message or follow our socials</em>
            <div class="sidebar-overlay"></div>
            <img src="assets/pictures/3.jpg" alt="img" class="responsive-image">
        </div>  
        <div class="sidebar-divider no-bottom"></div>
        <p class="sidebar-divider">Let's get social</p>
        <div class="sidebar-menu">
            <a class="default-link menu-item" href="https://www.facebook.com/enabled.labs">
                <i class="fa fa-facebook facebook-color"></i>
                <em>Facebook</em>
            </a>                   
            <a class="default-link menu-item" href="https://twitter.com/iEnabled">
                <i class="fa fa-twitter twitter-color"></i>
                <em>Twitter</em>
            </a>                 
            <a class="default-link menu-item" href="https://plus.google.com/u/1/100477648973116025417/posts">
                <i class="fa fa-google-plus google-color"></i>
                <em>Google Plus</em>
            </a>                    
            <a class="default-link menu-item" href="#">
                <i class="fa fa-youtube-play youtube-color"></i>
                <em>YouTube</em>
            </a>    
        </div>
        
        <p class="sidebar-divider">Admins Section</p>
        <div class="sidebar-menu">
            <a class="default-link menu-item" href="users/sign_in">
                <i class="fa fa-users bg-magenta-dark"></i>
                <em>Admin panel</em>
            </a>   
            <a class="menu-item close-sidebar" href="#">
                <i class="fa fa-times bg-red-dark"></i>
                <em>Close</em>
                <i class="fa fa-circle"></i>
            </a>
        </div>
    </div>
</div>

app/views/home/index.html.erb
<script type="text/javascript" src="assets/jquery.js"></script>
<script type="text/javascript" src="assets/plugins.js"></script>
<script type="text/javascript" src="assets/custom.js"></script>
<div id="page-transitions"></div>
    
<div class="page-preloader page-preloader-dark">
    <img class="page-preload" src="assets/preload.gif">
</div>
   
<div class="header header-dark">
    <a href="#" class="header-icon-1 show-left-sidebar"><i class="fa fa-navicon"></i></a>
    <a href="#" class="header-logo"></a>
    <a href="#" class="header-icon-4 show-right-sidebar"><i class="fa fa-envelope-o"></i></a>
</div>
<% x = 0 %>

    <div id="page-content" class="page-content">
        <% if !@posts.blank?  %>
        <% @posts.each do |y| %>
            <% x=x+1 %>
            <div id="<%= x %>" class="post_disable">
                <div class="responsive-video full-bottom">
                <!-- <iframe src="https://www.youtube.com/embed/0gv7OC9L2s8"></iframe> -->
                    <div style="background-image: url(assets/1.jpg); background-size: cover; background-position: center; height: 250px;" >
                    </div>
                </div>
                
                <div class="content">
                    <h4 class="center-text bold"><%= y.title %></h4>
                    <p class="boxed-text center-text half-bottom">
                        <%= y.body %>
                    </p>
                    <a href="#" class="scale-hover pinterest-color social-square post-prev"><i class="fa fa-arrow-left"></i></a>
                    <a href="#" class="pull-right pscale-hover button-blue social-square post-next"><i class="fa fa-arrow-right"></i></a>
                    <div class="decoration">
                    </div>
                </div>
            </div>
        <% end %>
        <% else %>
        <div class="responsive-video full-bottom">
                <!-- <iframe src="https://www.youtube.com/embed/0gv7OC9L2s8"></iframe> -->
                    <div style="background-image: url(assets/1.jpg); background-size: cover; background-position: center; height: 250px;" >
                    </div>
                </div>
           <div class="content">
                <p class="boxed-text center-text half-bottom">
                    <h4 class="center-text bold">No posts yet will add soon</h4> <br>
                    
                </p>
                <div style="margin-left: 42%">
                <a href="/" class="button button-blue"><i style="color: #fff">Take me back</i></a>

                </div>
                
            </div>
        <% end %>
    </div>

<script>
$(document).ready(function(){
    var a = 1;
    var b = <%= @posts.count if !@posts.nil? %>
    $('#'+a).removeClass( "post_disable").addClass('post_active');
    $(".post-next").click(function(){
        if(b>a)
        {
            
            $('#'+a).removeClass( "post_active").addClass('post_disable');
            a=a+1;
            $('#'+a).removeClass( "post_disable").addClass('post_active');
        }
      
    });

    $(".post-prev").click(function(){
        if(a>1)
        {
            $('#'+a).removeClass( "post_active").addClass('post_disable');
            a=a-1;
            $('#1').removeClass( "post_disable").addClass('post_active');

        }
        
    });
});

</script>

    

    

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Collegenews</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="viewport" content="user-scalable=no, initial-scale=1.0, maximum-scale=1.0 minimal-ui" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black">

<link rel="icon" type="image/png" href="images/splash/android-chrome-192x192.png" sizes="192x192">
<link rel="apple-touch-icon" sizes="196x196" href="images/splash/apple-touch-icon-196x196.png">
<link rel="apple-touch-icon" sizes="180x180" href="images/splash/apple-touch-icon-180x180.png">
<link rel="apple-touch-icon" sizes="152x152" href="images/splash/apple-touch-icon-152x152.png">
<link rel="apple-touch-icon" sizes="144x144" href="images/splash/apple-touch-icon-144x144.png">
<link rel="apple-touch-icon" sizes="120x120" href="images/splash/apple-touch-icon-120x120.png">
<link rel="apple-touch-icon" sizes="114x114" href="images/splash/apple-touch-icon-114x114.png">
<link rel="apple-touch-icon" sizes="76x76" href="images/splash/apple-touch-icon-76x76.png">
<link rel="apple-touch-icon" sizes="72x72" href="images/splash/apple-touch-icon-72x72.png">
<link rel="apple-touch-icon" sizes="60x60" href="images/splash/apple-touch-icon-60x60.png">
<link rel="apple-touch-icon" sizes="57x57" href="images/splash/apple-touch-icon-57x57.png">
<link rel="icon" type="image/png" href="images/splash/favicon-96x96.png" sizes="96x96">
<link rel="icon" type="image/png" href="images/splash/favicon-32x32.png" sizes="32x32">
<link rel="icon" type="image/png" href="images/splash/favicon-16x16.png" sizes="16x16">
<link rel="shortcut icon" href="images/splash/favicon.ico" type="image/x-icon" />
<link href='/assets/css0270.css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
<link href='/assets/csseb99.css?family=Satisfy' rel='stylesheet' type='text/css'>
  <link href='/assets/css0270.css?family=Roboto:400,100,100italic,300,300italic,400italic,500,500italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
	<link href='/assets/csseb99.css?family=Satisfy' rel='stylesheet' type='text/css'>

<link rel="stylesheet" type="text/css" href="/assets/style.css">
<link rel="stylesheet" type="text/css" href="/assets/menu.css">
<link rel="stylesheet" type="text/css" href="/assets/framework.css">

<script type="text/javascript" src="/assets/jquery.js"></script>
<script type="text/javascript" src="/assets/plugins.js"></script>
<script type="text/javascript" src="/assets/custom.js"></script>
</head>
<body>

<%= yield %>

<%= render "sidebar_left" %>
<%= render  "sidebar_right" %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
      <h5>New Post</h5>
      <strong>Title</strong>
      <em>required</em>
      <%= f.text_field :title, placeholder: "Enter the Title" %>                                 
      <strong>Content</strong>
      <em>required</em>
      <%= f.text_area :body, placeholder: "Enter the content" %>                                   
      <strong>Image Url</strong>
      <em>required</em>
      <%= f.text_field :image_url, placeholder: "Image Url" %>  

      <strong>Video url</strong>
      <em>required</em>
      <%= f.text_field :video_url, placeholder: "Video Url" %>  
      <strong>Category</strong>
      <em>required</em>
      <div class="store-input">
      <%= f.select :category_id, options_from_collection_for_select(@categories, "id", "name", @post.category_id) %>
      </div>
  </div>

  <a href="/posts" class="button button-green button-right full-top full-bottom"> Back</a>
  <a href="#" class="button button-green button-right full-top full-bottom">  <%= f.submit class:"login-button  button-green" %></a>
</div>
  <div class="clear"></div>

<% end %>

app/views/posts/edit.html.erb
<div id="page-transitions">
    
<div class="page-preloader page-preloader-dark">
    <img class="page-preload" src="assets/preload.gif">
</div>
   
<div class="header header-dark">
    <a href="#" class="header-icon-1 show-left-sidebar"><i class="fa fa-navicon"></i></a>
    <a href="#" class="header-logo"></a>
    <a href="#" class="header-icon-4 show-right-sidebar"><i class="fa fa-envelope-o"></i></a>
</div>


  <div id="page-content" class="page-content">
      <div id="page-content-scroll">       
          </div>
          
          <div class="content">
              
              <div class="page-blog">
                  <!-- POST 1-->
                  <div class="page-blog-list">
                              <div class="blog-post-comment-add">
							<h1>Editing Post</h1>

							<%= render 'form' %>

							<%= link_to 'Show', @post %> |
							<%= link_to 'Back', posts_path %>
						</div>
					</div>
				</div>
			</div>

app/views/posts/index.html.erb
<div id="page-transitions">
    
<div class="page-preloader page-preloader-dark">
    <img class="page-preload" src="assets/preload.gif">
</div>
   
<div class="header header-dark">
    <a href="#" class="header-icon-1 show-left-sidebar"><i class="fa fa-navicon"></i></a>
    <a href="#" class="header-logo"></a>
    <a href="#" class="header-icon-4 show-right-sidebar"><i class="fa fa-envelope-o"></i></a>
</div>
<div id="page-content" class="page-content">
    <div id="page-content-scroll">
        <div class="content">    
            <div class="decoration"></div>
              <p id="notice"><%= notice %></p>

              <h1>All post list</h1>

              

              <table>
                <thead>
                  <tr>
                  <th>slno</th>
                    <th>Title</th>
                    <th>Category</th>
                    <th colspan="3"></th>
                  </tr>
                </thead>

                <tbody>
                <% i=0 %>
                  <% @posts.each do |post| %>
                    <tr>
                      <td><%= i=i+1 %></td>
                      <td><%= post.title %></td>
                      <td><%= post.category.name %></td>
                      <td><%= link_to 'Show', post %></td>
                      <td><%= link_to 'Edit', edit_post_path(post) %></td>
                      <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                    </tr>
                  <% end %>
                </tbody>
              </table>
<%= link_to 'New Post', new_post_path %>
              <br>

              
          </div>
          </div>
          </div>
          </div>

app/views/posts/new.html.erb
<div id="page-transitions">
    
<div class="page-preloader page-preloader-dark">
    <img class="page-preload" src="assets/preload.gif">
</div>
   
<div class="header header-dark">
    <a href="#" class="header-icon-1 show-left-sidebar"><i class="fa fa-navicon"></i></a>
    <a href="#" class="header-logo"></a>
    <a href="#" class="header-icon-4 show-right-sidebar"><i class="fa fa-envelope-o"></i></a>
</div>

<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div id="page-transitions">
    
<div class="page-preloader page-preloader-dark">
    <img class="page-preload" src="assets/preload.gif">
</div>
   
<div class="header header-dark">
    <a href="#" class="header-icon-1 show-left-sidebar"><i class="fa fa-navicon"></i></a>
    <a href="#" class="header-logo"></a>
    <a href="#" class="header-icon-4 show-right-sidebar"><i class="fa fa-envelope-o"></i></a>
</div>

<div id="page-content" class="page-content">
    <div id="page-content-scroll">
        <div class="content">    
            <div class="decoration"></div>
               <%= link_to "Sign out", destroy_user_session_path, method: 'delete', class: "login-button button button-small button-green button-fullscreen full-bottom" %>
               <%= link_to "Posts", posts_path, class: "login-button button button-small bg-blue-dark button-fullscreen full-bottom" %>


<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<p>
  <strong>Image url:</strong>
  <%= @post.image_url %>
</p>

<p>
  <strong>Video url:</strong>
  <%= @post.video_url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @post.category.name %>
</p>

<%= link_to 'Edit', edit_post_path(@post), class: "button button-teal" %>
<%= link_to 'Back', posts_path,  class: "button button-green" %>

        </div>
    </div>
</div>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>